#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Diagnóstico rápido (Java, espaço em disco, tree)
        run: |
          java -version || true
          df -h || true
          du -sh . || true
          ls -la || true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # In pr-mode: 'true' Qodana checks only changed files
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
          upload-result: true
          # Memory limit for the Qodana container (in MB). A higher value helps avoid OOM.
          memory: 6144
          # quick-fixes available in Ultimate and Ultimate Plus plans
          push-fixes: 'none'
      - name: List Qodana results (if any)
        run: |
          echo "Listing potential results dirs"
          ls -la .qodana || true
          ls -la results || true
          ls -la qodana-results || true
